services:
  nahero-primary:
    image: postgres:15
    container_name: nahero-primary
    environment:
      POSTGRES_DB: ${NAHERO_DB}
      POSTGRES_USER: ${NAHERO_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5432:5432"
    volumes:
      - nahero_data_primary:/var/lib/postgresql/data
    networks:
      - nahero_network

  nahero-replica:
    image: postgres:15
    container_name: nahero-backup
    environment:
      POSTGRES_DB: ${NAHERO_DB}
      POSTGRES_USER: ${NAHERO_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5433:5432"
    volumes:
      - nahero_data_replica:/var/lib/postgresql/data
    networks:
      - nahero_network
    depends_on:
      - nahero-primary


  app:
    image: eclipse-temurin:23
    container_name: nahero-back
    environment:
      NAHERO_DB: ${NAHERO_DB}
      NAHERO_DB_USER: ${NAHERO_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NAHERO_JWT_TOKEN: ${NAHERO_JWT_TOKEN}
    volumes:
      - ./:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    networks:
      - nahero_network
    depends_on:
      - nahero-primary

volumes:
  nahero_data_primary:
  nahero_data_replica:

networks:
  nahero_network:
    driver: bridge