FROM eclipse-temurin:21-jdk-jammy

RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ci-settings.xml /usr/share/maven/conf/settings.xml

COPY pom.xml .
RUN mvn -B -Dmaven.artifact.threads=10 dependency:go-offline

COPY src/ ./src/

CMD ["mvn", "-B", "test"]
