INSERT INTO roles (name) VALUES
 ('IS_STUDENT'),
 ('IS_TEACHER'),
 ('IS_ADMIN'),
 ('IS_PREMIUM_STUDENT'),
 ('IS_PREMIUM_TEACHER');

INSERT INTO permissions (description) VALUES
('CAN_VIEW_USERS'),
('CAN_VIEW_FLASHCARDS'),
('CAN_CREATE_QUESTIONS'),
('CAN_CREATE_EXAMS'),
('CAN_CREATE_PRACTICE_EXAMS');