name: Java CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: nahero-vps
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ~/nahero/nahero-back
          
          git pull
          
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nahero-backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nahero-backend:latest
          
          cd ../nahero-docker
          docker compose pull backend
          docker compose up -d --build backend
